"""Shared utilities: config loading, paths, RNG helpers, small math helpers.

SYNTHETIC SIMULATION STUDY — no real animal data is used anywhere.
"""
from __future__ import annotations

import hashlib
import json
import os
from pathlib import Path
from typing import Any, Dict, Optional

import numpy as np
import yaml

# --------------------------------------------------------------------------
# Paths — everything is resolved relative to the repository root so the
# project can be cloned anywhere (no absolute paths).
# --------------------------------------------------------------------------
PKG_DIR = Path(__file__).resolve().parent
SRC_DIR = PKG_DIR.parent
REPO_ROOT = SRC_DIR.parent

PATHS = {
    "root": REPO_ROOT,
    "config": REPO_ROOT / "config.yaml",
    "seeds": REPO_ROOT / "seeds.yaml",
    "results": REPO_ROOT / "results",
    "results_raw": REPO_ROOT / "results" / "raw",
    "results_processed": REPO_ROOT / "results" / "processed",
    "figures": REPO_ROOT / "figures",
    "tables": REPO_ROOT / "tables",
    "models": REPO_ROOT / "models",
    "logs": REPO_ROOT / "logs",
    "paper": REPO_ROOT / "paper",
}

DISCLAIMER = (
    "Synthetic research simulation - not a veterinary decision tool. "
    "All data in this project are generated by a proof-of-concept dynamical model."
)


def ensure_dirs() -> None:
    for key, p in PATHS.items():
        if key in ("config", "seeds"):
            continue
        p.mkdir(parents=True, exist_ok=True)


_CONFIG_CACHE: Dict[str, Any] = {}


def load_config(path: Optional[os.PathLike] = None, refresh: bool = False) -> Dict[str, Any]:
    """Load config.yaml (cached)."""
    p = Path(path) if path is not None else PATHS["config"]
    key = str(p)
    if refresh or key not in _CONFIG_CACHE:
        with open(p, "r") as fh:
            _CONFIG_CACHE[key] = yaml.safe_load(fh)
    return _CONFIG_CACHE[key]


def load_seeds(path: Optional[os.PathLike] = None) -> Dict[str, Any]:
    p = Path(path) if path is not None else PATHS["seeds"]
    with open(p, "r") as fh:
        return yaml.safe_load(fh)


def deep_update(base: Dict[str, Any], overrides: Dict[str, Any]) -> Dict[str, Any]:
    """Recursively merge ``overrides`` into a deep copy of ``base``."""
    import copy

    out = copy.deepcopy(base)
    for k, v in (overrides or {}).items():
        if isinstance(v, dict) and isinstance(out.get(k), dict):
            out[k] = deep_update(out[k], v)
        else:
            out[k] = copy.deepcopy(v)
    return out


# --------------------------------------------------------------------------
# Deterministic seeding
# --------------------------------------------------------------------------
def stable_hash(*parts: Any) -> int:
    """Deterministic 32-bit hash of the string form of ``parts``.

    ``hash()`` is randomised per process in Python, so we use blake2b to make
    episode seeds reproducible across runs and machines.
    """
    payload = "|".join(str(p) for p in parts).encode("utf-8")
    digest = hashlib.blake2b(payload, digest_size=4).digest()
    return int.from_bytes(digest, "big")


def episode_seed(offset: int, *parts: Any) -> int:
    return int((offset + stable_hash(*parts)) % (2**31 - 1))


def make_rng(seed: int) -> np.random.Generator:
    return np.random.default_rng(int(seed) % (2**32 - 1))


# --------------------------------------------------------------------------
# Small math helpers
# --------------------------------------------------------------------------
def clip(x: float, lo: float, hi: float) -> float:
    return lo if x < lo else (hi if x > hi else x)


def relu(x: float) -> float:
    return x if x > 0.0 else 0.0


def gaussian_kernel(x: float, mu: float, sigma: float) -> float:
    z = (x - mu) / sigma
    return float(np.exp(-0.5 * z * z))


def truncated_normal(rng: np.random.Generator, mean: float, sd: float,
                     lo: float, hi: float, size: Optional[int] = None):
    """Draw from N(mean, sd) and clip to [lo, hi] (rejection-free, clipped)."""
    x = rng.normal(mean, sd, size=size)
    return np.clip(x, lo, hi)


def halflife_to_decay(halflife_hours: float, dt_minutes: float) -> float:
    """Per-step multiplicative decay factor for a given half-life."""
    steps_per_halflife = (halflife_hours * 60.0) / dt_minutes
    return float(0.5 ** (1.0 / steps_per_halflife))


def safe_float(x) -> float:
    v = float(x)
    if not np.isfinite(v):
        raise FloatingPointError(f"Non-finite value encountered: {x}")
    return v


# --------------------------------------------------------------------------
# I/O helpers
# --------------------------------------------------------------------------
def write_parquet_or_csv(df, path_no_ext: Path) -> Path:
    """Write Parquet when pyarrow is available, otherwise CSV."""
    path_no_ext = Path(path_no_ext)
    path_no_ext.parent.mkdir(parents=True, exist_ok=True)
    try:
        import pyarrow  # noqa: F401

        p = path_no_ext.with_suffix(".parquet")
        df.to_parquet(p, index=False)
        return p
    except Exception:
        p = path_no_ext.with_suffix(".csv")
        df.to_csv(p, index=False)
        return p


def read_table(path_no_ext: Path):
    """Read a table written by :func:`write_parquet_or_csv`."""
    import pandas as pd

    path_no_ext = Path(path_no_ext)
    pq = path_no_ext.with_suffix(".parquet")
    csv = path_no_ext.with_suffix(".csv")
    if pq.exists():
        return pd.read_parquet(pq)
    if csv.exists():
        return pd.read_csv(csv)
    raise FileNotFoundError(f"Neither {pq} nor {csv} exists. Run the experiments first.")


def save_json(obj: Any, path: Path) -> None:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    def _default(o):
        if isinstance(o, (np.integer,)):
            return int(o)
        if isinstance(o, (np.floating,)):
            return float(o)
        if isinstance(o, np.ndarray):
            return o.tolist()
        if isinstance(o, Path):
            return str(o)
        return str(o)

    with open(path, "w") as fh:
        json.dump(obj, fh, indent=2, default=_default)


def banner(text: str, width: int = 74) -> str:
    line = "=" * width
    return f"\n{line}\n{text}\n{line}"
